REGION_NAME_MAP = {
    "ES11": "Galicia",
    "ES12": "Principado de Asturias",
    "ES13": "Cantabria",
    "ES21": "País Vasco",
    "ES22": "Comunidad Foral de Navarra",
    "ES23": "La Rioja",
    "ES24": "Aragón",
    "ES30": "Comunidad de Madrid",
    "ES41": "Castilla y León",
    "ES42": "Castilla-La Mancha",
    "ES43": "Extremadura",
    "ES51": "Cataluña",
    "ES52": "Comunidad Valenciana",
    "ES53": "Illes Balears",
    "ES61": "Andalucía",
    "ES62": "Región de Murcia",
    "ES63": "Ciudad Autónoma de Ceuta",
    "ES64": "Ciudad Autónoma de Melilla",
    "ES70": "Canarias",
    "ESZZ": "Extra-Regio",
}

POLICY_REGION_TO_NUTS_ENG = {
    "Andalusia": "ES61",
    "Aragon": "ES24",
    "Asturias": "ES12",
    "Balearic Islands": "ES53",
    "Canary Islands": "ES70",
    "Cantabria": "ES13",
    "Castilla-La Mancha": "ES42",
    "Castilla y Leon": "ES41",
    "Catalonia": "ES51",
    "Ceuta": "ES63",
    "Extremadura": "ES43",
    "Galicia": "ES11",
    "Madrid": "ES30",
    "Melilla": "ES64",
    "Murcia": "ES62",
    "Navarra": "ES22",
    "Basque Country": "ES21",
    "La Rioja": "ES23",
    "Valencia": "ES52",
}

PERSON_HOUSEHOLD_COLUMNS = [
    "household_id",
    "year",
    "region_code",
    "region_name",
    "weight_hh",
    "household_size",
    "n_adults",
    "n_children",
    "income_before_transfers_annual",
    "income_after_transfers_annual",
    "resources_proxy_baseline_monthly",
    "resources_proxy_excl_capital_monthly",
    "labour_income_hh_annual",
    "labour_income_hh_monthly",
    "any_positive_labour_income",
    "wealth_proxy_strict",
    "any_active_job_search",
    "all_unemployed_searching",
    "hh_social_assistance_income_annual",
    "any_social_assistance_income_hh",
    "any_foreign_nationality_hh",
    "any_responsible_person_claimant_eligible",
    "any_responsible_person_active_search",
    "poverty",
    "matdep",
]

HOUSEHOLD_REQUIRED_COLUMNS = [
    "resources_proxy_baseline_monthly",
    "resources_proxy_excl_capital_monthly",
    "household_size",
    "n_adults_18plus",
    "n_adults_23plus",
    "n_adults_25plus",
    "weight_hh",
    "single_adult",
    "single_parent",
    "two_adults",
    "threeplus_adults",
    "wealth_proxy_strict",
    "responsible_person_proxy_available",
    "rp1_age",
    "rp2_age",
    "rp1_claimant_activity_eligible",
    "rp2_claimant_activity_eligible",
    "any_responsible_person_claimant_eligible",
    "any_responsible_person_active_search",
    "labour_income_hh_annual",
    "labour_income_hh_monthly",
    "any_positive_labour_income",
    "any_unemployed_18_64",
    "all_working_age_nonworking",
    "n_working_18_64",
    "n_unemployed_18_64",
    "hh_social_assistance_income_annual",
    "any_social_assistance_income_hh",
    "n_students_18_64",
    "n_retired_18_64",
    "n_disabled_18_64",
    "has_labour_composition",
    "has_complete_age_composition",
    "labour_income_observed",
    "all_unemployed_searching",
]

MAX_REASONABLE_AGE = 125
